#---------------------------------------------------#
## é…ç½®æ–‡ä»¶éœ€è¦æ”¾ç½®åœ¨ $HOME/.config/clash/*.yaml

## è¿™ä»½æ–‡ä»¶æ˜¯clashXçš„åŸºç¡€é…ç½®æ–‡ä»¶ï¼Œè¯·å°½é‡æ–°å»ºé…ç½®æ–‡ä»¶è¿›è¡Œä¿®æ”¹ã€‚
## ï¼ï¼ï¼åªæœ‰è¿™ä»½æ–‡ä»¶çš„ç«¯å£è®¾ç½®ä¼šéšClashXå¯åŠ¨ç”Ÿæ•ˆ

## å¦‚æœæ‚¨ä¸çŸ¥é“å¦‚ä½•æ“ä½œï¼Œè¯·å‚é˜… SS-Rule-Snippetï¼šhttps://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yaml
## æˆ–è€…å®˜æ–¹Githubæ–‡æ¡£ https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# Port of HTTP(S) proxy server on the local end
# port: 7890

# Port of SOCKS5 proxy server on the local end
# socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule / global / direct / script (default is rule)
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# silent / error / warning / info / debug
log-level: warning

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
# external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0

proxies:

proxy-groups:
  # - name: relay
  #   type: relay
  #   proxies:
  #     - select
  #     - http
  #     - vmess
  #   # disable-udp: true

  - name: Proxy        # å…¨å±€é€‰æ‹©
    type: select
    proxies:
      - auto           # å»¶è¿Ÿæœ€ä½
      - é€‰æ‹©å›½å®¶
      - é€‰æ‹©èŠ‚ç‚¹
      - fallback-auto  # å¤±è´¥åˆ‡æ¢
      - load-balance   # è´Ÿè½½å‡è¡¡

  # å»¶è¿Ÿæœ€ä½
  - name: auto
    type: url-test
    use:
      - shadowsocks
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # tolerance: 50
    # lazy: true
    # disable-udp: true

  # é€‰æ‹©èŠ‚ç‚¹
  - name: é€‰æ‹©èŠ‚ç‚¹
    type: select
    use:
      - shadowsocks
      - all

  # è´Ÿè½½å‡è¡¡
  - name: load-balance
    type: load-balance
    use:
      - shadowsocks
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: true
    # disable-udp: true
    # strategy: consistent-hashing  # or round-robin

  # å¤±è´¥åˆ‡æ¢
  - name: fallback-auto
    type: fallback
    proxies:
      - DIRECT
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: true
    # disable-udp: true

  - name: é€‰æ‹©å›½å®¶
    type: select
    proxies:
      - ğŸ‡¨ğŸ‡³ ä¸­å›½
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
      - ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯
      - ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºš
      - ğŸ‡¨ğŸ‡­ ç‘å£«
      - ğŸ‡©ğŸ‡ª å¾·å›½
      - ğŸ‡«ğŸ‡· æ³•å›½
      - ğŸ‡¬ğŸ‡§ è‹±å›½
      - ğŸ‡³ğŸ‡± è·å…°
      - å…¶ä»–å›½å®¶

  - name: Domestic
    type: select
    use:
      - shadowsocks
    proxies:
      - DIRECT

  - name: Others
    type: select
    use:
      - shadowsocks
    proxies:
      - Proxy
      - DIRECT
      - Domestic

  - name: ğŸ‡¨ğŸ‡³ ä¸­å›½
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - cn

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - jp

  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - sg

  - name: ğŸ‡ºğŸ‡¸ ç¾å›½
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - us

  - name: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - ca

  - name: ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - ru

  - name: ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºš
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - au

  - name: ğŸ‡¨ğŸ‡­ ç‘å£«
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - ch

  - name: ğŸ‡©ğŸ‡ª å¾·å›½
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - de

  - name: ğŸ‡«ğŸ‡· æ³•å›½
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - fr

  - name: ğŸ‡¬ğŸ‡§ è‹±å›½
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - gb

  - name: ğŸ‡³ğŸ‡± è·å…°
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - nl

  - name: å…¶ä»–å›½å®¶
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - others

  - name: AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
      - Proxy

  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxy

# proxy-providers:
#   remoteproxy:  # name of the provider, in this example the name of proxy-provider is remoteproxy
#     type:       # type of the provider, it can be a HTTP or a File
#     path:       # where is the file, ./ relative to clash home
#     url:        # only available when type is HTTP, where to download a file. You don't need to create a new file in local space.
#     interval:   # auto-update interval,only available when type is HTTP
#     health-check: #health check option start at here
#       enable:
#       url:
#       interval:

proxy-providers:
  shadowsocks:
    type: http
    url: https://raw.githubusercontent.com/issenn/clash-config/master/proxies/providers/shadowsocks.yaml
    path: ./proxies/providers/shadowsocks.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  all:
    type: http
    url: "https://ednovas.design/clash/proxies"
    path: ednovas.design/provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  cn:
    type: http
    url: "https://ednovas.design/clash/proxies?c=CN,HK,TW"
    path: ednovas.design/provider-cn.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  jp:
    type: http
    url: "https://ednovas.design/clash/proxies?c=JP"
    path: ednovas.design/provider-jp.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  sg:
    type: http
    url: "https://ednovas.design/clash/proxies?c=SG"
    path: ednovas.design/provider-sg.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  us:
    type: http
    url: "https://ednovas.design/clash/proxies?c=US"
    path: ednovas.design/provider-us.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  ca:
    type: http
    url: "https://ednovas.design/clash/proxies?c=CA"
    path: ednovas.design/provider-ca.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  ru:
    type: http
    url: "https://ednovas.design/clash/proxies?c=RU"
    path: ednovas.design/provider-ru.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  au:
    type: http
    url: "https://ednovas.design/clash/proxies?c=AU"
    path: ednovas.design/provider-au.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  ch:
    type: http
    url: "https://ednovas.design/clash/proxies?c=CH"
    path: ednovas.design/provider-ch.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  de:
    type: http
    url: "https://ednovas.design/clash/proxies?c=DE"
    path: ednovas.design/provider-de.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  fr:
    type: http
    url: "https://ednovas.design/clash/proxies?c=FR"
    path: ednovas.design/provider-fr.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  gb:
    type: http
    url: "https://ednovas.design/clash/proxies?c=GB"
    path: ednovas.design/provider-gb.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  nl:
    type: http
    url: "https://ednovas.design/clash/proxies?c=NL"
    path: ednovas.design/provider-nl.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  others:
    type: http
    url: "https://ednovas.design/clash/proxies?nc=CN,HK,TW,US,CA,JP,SG,AU,CH,DE,GB,NL,FR,RU"
    path: ednovas.design/provider-others.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

rules:
  - RULE-SET,google,Proxy
  - GEOIP,CN,DIRECT
  # - MATCH,Proxy
  - MATCH,DIRECT

# rule-providers:
#   externalrule:   # name of the providerï¼Œin this example the name of the rule-provider is externalrule
#     type:         # type of the provider, it can be a HTTP or a File
#     behavior:     # the type of rules
#     path:         # where is the file, ./ relative to clash home
#     url:          # only available when type is HTTP, where to download a file. You don't need to create a new file in local space.
#     interval:     # auto-update interval,only available when type is HTTP

rule-providers:
  google:
    type: http
    behavior: domain
    path: ./rules/providers/google.yaml
    url: https://raw.githubusercontent.com/issenn/clash-config/master/rules/providers/google.yaml
    interval: 86400
