#---------------------------------------------------#
## é…ç½®æ–‡ä»¶éœ€è¦æ”¾ç½®åœ¨ $HOME/.config/clash/*.yaml

## è¿™ä»½æ–‡ä»¶æ˜¯clashXçš„åŸºç¡€é…ç½®æ–‡ä»¶ï¼Œè¯·å°½é‡æ–°å»ºé…ç½®æ–‡ä»¶è¿›è¡Œä¿®æ”¹ã€‚
## ï¼ï¼ï¼åªæœ‰è¿™ä»½æ–‡ä»¶çš„ç«¯å£è®¾ç½®ä¼šéšClashXå¯åŠ¨ç”Ÿæ•ˆ

## å¦‚æžœæ‚¨ä¸çŸ¥é“å¦‚ä½•æ“ä½œï¼Œè¯·å‚é˜… SS-Rule-Snippetï¼šhttps://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yaml
## æˆ–è€…å®˜æ–¹Githubæ–‡æ¡£ https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# Port of HTTP(S) proxy server on the local end
# port: 7890

# Port of SOCKS5 proxy server on the local end
# socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule / global / direct / script (default is rule)
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# silent / error / warning / info / debug
log-level: warning

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
# external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0

proxies:

proxy-groups:
  # - name: relay
  #   type: relay
  #   proxies:
  #     - select
  #     - http
  #     - vmess
  #   # disable-udp: true

  - name: Proxy        # å…¨å±€é€‰æ‹©
    type: select
    proxies:
      - Auto           # å»¶è¿Ÿæœ€ä½Ž
      - Country        # é€‰æ‹©å›½å®¶
      - Node           # é€‰æ‹©èŠ‚ç‚¹
      - Fallback-auto  # å¤±è´¥åˆ‡æ¢
      - Load-balance   # è´Ÿè½½å‡è¡¡

  # å»¶è¿Ÿæœ€ä½Ž
  - name: Auto
    type: url-test
    proxies:
      - Foreign-auto
      # - Domestic-auto
    use:
      - shadowsocks
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # tolerance: 50
    # lazy: true
    # disable-udp: true

  # é€‰æ‹©èŠ‚ç‚¹
  - name: Node
    type: select
    use:
      - shadowsocks
      - all

  # è´Ÿè½½å‡è¡¡
  - name: Load-balance
    type: load-balance
    use:
      - shadowsocks
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: true
    # disable-udp: true
    # strategy: consistent-hashing  # or round-robin

  # å¤±è´¥åˆ‡æ¢
  - name: Fallback-auto
    type: fallback
    use:
      - shadowsocks
      - all
    proxies:
      - Domestic
      - DIRECT
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: true
    # disable-udp: true

  # é€‰æ‹©å›½å®¶
  - name: Country
    type: select
    proxies:
      - Domestic
      - Foreign
      - ðŸ‡¨ðŸ‡³ ä¸­å›½
      - ðŸ‡¯ðŸ‡µ æ—¥æœ¬
      - ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡
      - ðŸ‡ºðŸ‡¸ ç¾Žå›½
      - ðŸ‡¨ðŸ‡¦ åŠ æ‹¿å¤§
      - ðŸ‡·ðŸ‡º ä¿„ç½—æ–¯
      - ðŸ‡¦ðŸ‡º æ¾³å¤§åˆ©äºš
      - ðŸ‡¨ðŸ‡­ ç‘žå£«
      - ðŸ‡©ðŸ‡ª å¾·å›½
      - ðŸ‡«ðŸ‡· æ³•å›½
      - ðŸ‡¬ðŸ‡§ è‹±å›½
      - ðŸ‡³ðŸ‡± è·å…°
      - å…¶ä»–å›½å®¶

  # é€‰æ‹©å›½å†…
  - name: Domestic
    type: select
    proxies:
      - Domestic-auto
      - DIRECT
      - ðŸ‡¨ðŸ‡³ ä¸­å›½

  - name: Domestic-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
      - DIRECT
      - ðŸ‡¨ðŸ‡³ ä¸­å›½-auto

  # é€‰æ‹©å›½å¤–
  - name: Foreign
    type: select
    proxies:
      - Foreign-auto
      - ðŸ‡¯ðŸ‡µ æ—¥æœ¬
      - ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡
      - ðŸ‡ºðŸ‡¸ ç¾Žå›½
      - ðŸ‡¨ðŸ‡¦ åŠ æ‹¿å¤§
      - ðŸ‡·ðŸ‡º ä¿„ç½—æ–¯
      - ðŸ‡¦ðŸ‡º æ¾³å¤§åˆ©äºš
      - ðŸ‡¨ðŸ‡­ ç‘žå£«
      - ðŸ‡©ðŸ‡ª å¾·å›½
      - ðŸ‡«ðŸ‡· æ³•å›½
      - ðŸ‡¬ðŸ‡§ è‹±å›½
      - ðŸ‡³ðŸ‡± è·å…°
      - å…¶ä»–å›½å®¶

  - name: Foreign-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
      - ðŸ‡¯ðŸ‡µ æ—¥æœ¬-auto
      - ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡-auto
      - ðŸ‡ºðŸ‡¸ ç¾Žå›½-auto
      - ðŸ‡¨ðŸ‡¦ åŠ æ‹¿å¤§-auto
      - ðŸ‡·ðŸ‡º ä¿„ç½—æ–¯-auto
      - ðŸ‡¦ðŸ‡º æ¾³å¤§åˆ©äºš-auto
      - ðŸ‡¨ðŸ‡­ ç‘žå£«-auto
      - ðŸ‡©ðŸ‡ª å¾·å›½-auto
      - ðŸ‡«ðŸ‡· æ³•å›½-auto
      - ðŸ‡¬ðŸ‡§ è‹±å›½-auto
      - ðŸ‡³ðŸ‡± è·å…°-auto
      - å…¶ä»–å›½å®¶-auto

  - name: Others
    type: select
    use:
      - shadowsocks
    proxies:
      - Proxy
      - DIRECT
      - Domestic

  - name: ðŸ‡¨ðŸ‡³ ä¸­å›½
    type: select
    proxies:
      - ðŸ‡¨ðŸ‡³ ä¸­å›½-auto
    use:
      - cn

  - name: ðŸ‡¨ðŸ‡³ ä¸­å›½-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - cn

  - name: ðŸ‡¯ðŸ‡µ æ—¥æœ¬
    type: select
    proxies:
      - ðŸ‡¯ðŸ‡µ æ—¥æœ¬-auto
    use:
      - jp

  - name: ðŸ‡¯ðŸ‡µ æ—¥æœ¬-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - jp

  - name: ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡
    type: select
    proxies:
      - ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡-auto
    use:
      - sg

  - name: ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - sg

  - name: ðŸ‡ºðŸ‡¸ ç¾Žå›½
    type: select
    proxies:
      - ðŸ‡ºðŸ‡¸ ç¾Žå›½-auto
    use:
      - us

  - name: ðŸ‡ºðŸ‡¸ ç¾Žå›½-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - us

  - name: ðŸ‡¨ðŸ‡¦ åŠ æ‹¿å¤§
    type: select
    proxies:
      - ðŸ‡¨ðŸ‡¦ åŠ æ‹¿å¤§-auto
    use:
      - ca

  - name: ðŸ‡¨ðŸ‡¦ åŠ æ‹¿å¤§-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - ca

  - name: ðŸ‡·ðŸ‡º ä¿„ç½—æ–¯
    type: select
    proxies:
      - ðŸ‡·ðŸ‡º ä¿„ç½—æ–¯-auto
    use:
      - ru

  - name: ðŸ‡·ðŸ‡º ä¿„ç½—æ–¯-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - ru

  - name: ðŸ‡¦ðŸ‡º æ¾³å¤§åˆ©äºš
    type: select
    proxies:
      - ðŸ‡¦ðŸ‡º æ¾³å¤§åˆ©äºš-auto
    use:
      - au

  - name: ðŸ‡¦ðŸ‡º æ¾³å¤§åˆ©äºš-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - au

  - name: ðŸ‡¨ðŸ‡­ ç‘žå£«
    type: select
    proxies:
      - ðŸ‡¨ðŸ‡­ ç‘žå£«-auto
    use:
      - ch

  - name: ðŸ‡¨ðŸ‡­ ç‘žå£«-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - ch

  - name: ðŸ‡©ðŸ‡ª å¾·å›½
    type: select
    proxies:
      - ðŸ‡©ðŸ‡ª å¾·å›½-auto
    use:
      - de

  - name: ðŸ‡©ðŸ‡ª å¾·å›½-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - de

  - name: ðŸ‡«ðŸ‡· æ³•å›½
    type: select
    proxies:
      - ðŸ‡«ðŸ‡· æ³•å›½-auto
    use:
      - fr

  - name: ðŸ‡«ðŸ‡· æ³•å›½-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - fr

  - name: ðŸ‡¬ðŸ‡§ è‹±å›½
    type: select
    proxies:
      - ðŸ‡¬ðŸ‡§ è‹±å›½-auto
    use:
      - gb

  - name: ðŸ‡¬ðŸ‡§ è‹±å›½-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - gb

  - name: ðŸ‡³ðŸ‡± è·å…°
    type: select
    proxies:
      - ðŸ‡³ðŸ‡± è·å…°-auto
    use:
      - nl

  - name: ðŸ‡³ðŸ‡± è·å…°-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - nl

  - name: å…¶ä»–å›½å®¶
    type: select
    proxies:
      - å…¶ä»–å›½å®¶-auto
    use:
      - others

  - name: å…¶ä»–å›½å®¶-auto
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - others

  # Apple æœåŠ¡ä»£ç†
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxy

  # å›½é™…æµåª’ä½“æœåŠ¡
  # - name: "GlobalMedia"
  #   type: select
  #   proxies:
  #     - "Proxy"

  # å¤§é™†æµåª’ä½“é¢å‘æ¸¯æ¾³å°é™å®šæœåŠ¡
  # - name: "HKMTMedia"
  #   type: select
  #   proxies:
  #     - "DIRECT"

  # è¿è¥å•†åŠå£°åç‹¼è—‰ç½‘ç«™åŠ«æŒ
  # - name: "Hijacking"
  #   type: select
  #   proxies:
  #     - "REJECT"
  #     - "DIRECT"

  - name: AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
      - Proxy

  - name: Final
    type: select
    proxies:
      - DIRECT
      - Proxy

# proxy-providers:
#   remoteproxy:  # name of the provider, in this example the name of proxy-provider is remoteproxy
#     type:       # type of the provider, it can be a HTTP or a File
#     path:       # where is the file, ./ relative to clash home
#     url:        # only available when type is HTTP, where to download a file. You don't need to create a new file in local space.
#     interval:   # auto-update interval,only available when type is HTTP
#     health-check: #health check option start at here
#       enable:
#       url:
#       interval:

proxy-providers:
  shadowsocks:
    type: http
    url: https://raw.githubusercontent.com/issenn/clash-config/master/proxies/providers/shadowsocks.yaml
    path: ./proxies/providers/shadowsocks.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  all:
    type: http
    url: "https://ednovas.design/clash/proxies"
    path: ednovas.design/provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  cn:
    type: http
    url: "https://ednovas.design/clash/proxies?c=CN,HK,TW"
    path: ednovas.design/provider-cn.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  jp:
    type: http
    url: "https://ednovas.design/clash/proxies?c=JP"
    path: ednovas.design/provider-jp.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  sg:
    type: http
    url: "https://ednovas.design/clash/proxies?c=SG"
    path: ednovas.design/provider-sg.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  us:
    type: http
    url: "https://ednovas.design/clash/proxies?c=US"
    path: ednovas.design/provider-us.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  ca:
    type: http
    url: "https://ednovas.design/clash/proxies?c=CA"
    path: ednovas.design/provider-ca.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  ru:
    type: http
    url: "https://ednovas.design/clash/proxies?c=RU"
    path: ednovas.design/provider-ru.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  au:
    type: http
    url: "https://ednovas.design/clash/proxies?c=AU"
    path: ednovas.design/provider-au.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  ch:
    type: http
    url: "https://ednovas.design/clash/proxies?c=CH"
    path: ednovas.design/provider-ch.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  de:
    type: http
    url: "https://ednovas.design/clash/proxies?c=DE"
    path: ednovas.design/provider-de.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  fr:
    type: http
    url: "https://ednovas.design/clash/proxies?c=FR"
    path: ednovas.design/provider-fr.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  gb:
    type: http
    url: "https://ednovas.design/clash/proxies?c=GB"
    path: ednovas.design/provider-gb.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  nl:
    type: http
    url: "https://ednovas.design/clash/proxies?c=NL"
    path: ednovas.design/provider-nl.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  others:
    type: http
    url: "https://ednovas.design/clash/proxies?nc=CN,HK,TW,US,CA,JP,SG,AU,CH,DE,GB,NL,FR,RU"
    path: ednovas.design/provider-others.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

rules:
  - RULE-SET,google,Proxy

  # > Apple
  - DOMAIN-SUFFIX,aaplimg.com,Apple
  - DOMAIN-SUFFIX,apple.co,Apple
  - DOMAIN-SUFFIX,apple.com,Apple
  - DOMAIN-SUFFIX,apple-cloudkit.com,Apple
  - DOMAIN-SUFFIX,appstore.com,Apple
  - DOMAIN-SUFFIX,cdn-apple.com,Apple
  - DOMAIN-SUFFIX,crashlytics.com,Apple
  - DOMAIN-SUFFIX,icloud.com,Apple
  - DOMAIN-SUFFIX,icloud-content.com,Apple
  - DOMAIN-SUFFIX,me.com,Apple
  - DOMAIN-SUFFIX,mzstatic.com,Apple
  - DOMAIN,www-cdn.icloud.com.akadns.net,Apple
  - IP-CIDR,17.0.0.0/8,Apple,no-resolve

  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT

  # DNSPod Public DNS+
  - IP-CIDR,119.28.28.28/32,DIRECT,no-resolve

  # GeoIP China
  - GEOIP,CN,DIRECT

  - MATCH,Final

# rule-providers:
#   externalrule:   # name of the providerï¼Œin this example the name of the rule-provider is externalrule
#     type:         # type of the provider, it can be a HTTP or a File
#     behavior:     # the type of rules
#     path:         # where is the file, ./ relative to clash home
#     url:          # only available when type is HTTP, where to download a file. You don't need to create a new file in local space.
#     interval:     # auto-update interval,only available when type is HTTP

rule-providers:
  google:
    type: http
    behavior: domain
    path: ./rules/providers/google.yaml
    url: https://raw.githubusercontent.com/issenn/clash-config/master/rules/providers/google.yaml
    interval: 86400
